a = 1 # a is an integer
b = 2.0 # b is a float
c = 3 + 4j # c is a complex number
d = True # d is a boolean
e = "Hello" # e is a string
f = [1, 2, 3] # f is a list
g = (1, 2, 3) # g is a tuple
h = {1: "one", 2: "two", 3: "three"} # h is a dictionary
i = False # i is a boolean
j = None # j is a NoneType